# Generated by Django 5.0.14 on 2025-11-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresosolicitud',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
